format_version = 1

welcome_message = """
Is this your first time? Don't worry, Sharplings is made for beginners!
We are going to teach you a lot of things about C#, but before we can
get started, here are some notes about how Sharplings operates:

1. The central concept behind Sharplings is that you solve exercises. These
   exercises usually contain some compiler or logic errors which cause the
   exercise to fail compilation or testing. It's your job to find all errors
   and fix them!
2. Make sure to have your editor open in the `Sharplings/` directory. Sharplings
   will show you the path of the current exercise under the progress bar. Open
   the exercise file in your editor, fix errors and save the file. Sharplings
   will automatically detect the file change and rerun the exercise. If all
   errors are fixed, Sharplings will ask you to move on to the next exercise.
3. If you're stuck on an exercise, enter `h` to show a hint.
4. If an exercise doesn't make sense to you, feel free to open an issue on
   GitHub! (https://github.com/C6OI/Sharplings). We look at every issue, and
   sometimes, other learners do too so you can help each other out!"""

final_message = """
We hope you enjoyed learning about the various aspects of C#!
If you noticed any issues, don't hesitate to report them on GitHub.
You can also contribute your own exercises to help the greater community!
Also, we highly recommend you check out Rustlings, which is the project that Sharplings was built on."""

# INTRO

[[exercises]]
name = "Intro1"
directory = "00_Intro"
test = false
skip_check_unsolved = true
hint = """
Enter `n` to move on to the next exercise.
You might need to press ENTER after typing `n`."""

[[exercises]]
name = "Intro2"
directory = "00_Intro"
test = false
hint = "The compiler is informing us that we've got the name of the WriteLine method wrong."
