format_version = 1

welcome_message = """
Is this your first time? Don't worry, Sharplings is made for beginners!
We are going to teach you a lot of things about C#, but before we can
get started, here are some notes about how Sharplings operates:

1. The central concept behind Sharplings is that you solve exercises. These
   exercises usually contain some compiler or logic errors which cause the
   exercise to fail compilation or testing. It's your job to find all errors
   and fix them!
2. Make sure to have your editor open in the `Sharplings/` directory. Sharplings
   will show you the path of the current exercise under the progress bar. Open
   the exercise file in your editor, fix errors and save the file. Sharplings
   will automatically detect the file change and rerun the exercise. If all
   errors are fixed, Sharplings will ask you to move on to the next exercise.
3. If you're stuck on an exercise, enter `h` to show a hint.
4. If an exercise doesn't make sense to you, feel free to open an issue on
   GitHub! (https://github.com/C6OI/Sharplings). We look at every issue, and
   sometimes, other learners do too so you can help each other out!"""

final_message = """
We hope you enjoyed learning about the various aspects of C#!
If you noticed any issues, don't hesitate to report them on GitHub.
You can also contribute your own exercises to help the greater community!
Also, we highly recommend you check out Rustlings, which is the project
that Sharplings was built on."""

# INTRO

[[exercises]]
name = "Intro1"
directory = "00_Intro"
test = false
skip_check_unsolved = true
hint = """
Enter `n` to move on to the next exercise.
You might need to press ENTER after typing `n`."""

[[exercises]]
name = "Intro2"
directory = "00_Intro"
test = false
hint = """
The compiler is informing us that we've got the name of the WriteLine
method wrong."""

# VARIABLES

[[exercises]]
name = "Variables1"
directory = "01_Variables"
test = false
hint = """
The declaration in the `Main` method is missing a keyword that is needed
in C# to create a new variable."""

[[exercises]]
name = "Variables2"
directory = "01_Variables"
test = false
hint = """
The compiler message is saying that C# can't infer the type that the
variable binding `x` has with what is given here.

What happens if you explicitly specify the type of the first line in
the `Main` method?

What if you give `x` a value?

What if you do both?

What type should `x` be, anyway?

What if `x` is the same type as `10`? What if it's a different type?"""

[[exercises]]
name = "Variables3"
directory = "01_Variables"
test = false
hint = """
In this exercise, we have a variable that we've created in the `Main` method,
and we're trying to use it in the next line, but we haven't given it a value.

We can't print out something that isn't there; try giving `x` a value!

This is an error that can cause bugs that's very easy to make in any
programming language -- thankfully the C# compiler has caught this for us!"""

[[exercises]]
name = "Variables4"
directory = "01_Variables"
test = false
hint = """
In this exercise, the compiler is complaining that it doesn't know
the type of the constant `x`.

Unlike variables, which can use `var` for type inference, constants declared
with the `const` keyword must always have their type explicitly specified.

Try adding a type between `const` and `x`. What type should a value like `42` be?"""

[[exercises]]
name = "Variables5"
directory = "01_Variables"
test = false
hint = """
The compiler is complaining that the value of `x` cannot be used to initialize
the constant `y`.

Constants in C# must be initialized with values that are known at compile-time.
Since `x` is a variable, its value could potentially change, so it's not a
compile-time constant.

What keyword would you need to add to `x` to make it a compile-time constant?"""

[[exercises]]
name = "Variables6"
directory = "01_Variables"
test = false
hint = """
The compiler is telling us that a constant cannot be assigned after declaration.

In C#, constants must be initialized at the same time they are declared.
You cannot declare a constant on one line and assign its value on another.

Try combining the declaration and initialization into a single statement."""

# METHODS

[[exercises]]
name = "Methods1"
directory = "02_Methods"
test = false
hint = """
This `Main` method is calling a method that it expects to exist, but the
method doesn't exist. It expects this function to have the name `CallMe`.
It also expects this method to not take any arguments and not return a value.
Sounds a lot like `Main`, doesn't it?"""

[[exercises]]
name = "Methods2"
directory = "02_Methods"
test = false
hint = """
C# requires that all parts of a method's signature have type specified,
but `CallMe` is missing the type of `num`."""

[[exercises]]
name = "Methods3"
directory = "02_Methods"
test = false
hint = """
This time, the method *declaration* is okay, but there's something wrong
with the place where we are calling the method."""

[[exercises]]
name = "Methods4"
directory = "02_Methods"
test = false
hint = """
The error message points to the method `SalePrice` and says that return type is `void`.
Take a look at the `IsEven` method for an example!"""

[[exercises]]
name = "Methods5"
directory = "02_Methods"
test = false
hint = """
The error indicates that return statement is missing. The `Square` method
is declared to return an `int`, but the calculation `num * num` is just an
expression that isn't being returned.

There are two ways to fix this:
1. Add the `return` keyword before `num * num;`
2. Use an expression-bodied method with the `=>` syntax instead of a block body."""
